# Site settings
title: Scraping Enthusiast
email: admin@scrapingenthusiast.com
description: >-
  Learn no-code web scraping from the experts at Novi Develop. Master data
  extraction tools for TikTok, X.com, and more with step-by-step tutorials.
baseurl: ""
url: "https://scrapingenthusiast.com"
twitter_username: scrapingenthusiast
github_username: scrapingenthusiast
author: Novi Develop

# Custom variables
timezone: Asia/Ho_Chi_Minh
tagline: "No-Code Web Scraping"
hero_title: "Learn Data Extraction "
hero_highlight: "The No-Code Way"

# Build settings
layouts_dir: shared/_layouts
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalink style
permalink: /:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Novi Develop"
